// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kagal/v1/agent.proto

package kagal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hello is the initial handshake from agent to server.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BootCount     uint32                 `protobuf:"varint,2,opt,name=boot_count,json=bootCount,proto3" json:"boot_count,omitempty"`
	HwSerial      string                 `protobuf:"bytes,3,opt,name=hw_serial,json=hwSerial,proto3" json:"hw_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_kagal_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_kagal_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Hello) GetBootCount() uint32 {
	if x != nil {
		return x.BootCount
	}
	return 0
}

func (x *Hello) GetHwSerial() string {
	if x != nil {
		return x.HwSerial
	}
	return ""
}

// StatusReport is a periodic status update from agent to server.
type StatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Meta          *structpb.Struct       `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_kagal_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_kagal_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReport) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusReport) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Quarantine notifies the agent it has been quarantined.
type Quarantine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	ClaimCode     string                 `protobuf:"bytes,2,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quarantine) Reset() {
	*x = Quarantine{}
	mi := &file_kagal_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quarantine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quarantine) ProtoMessage() {}

func (x *Quarantine) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quarantine.ProtoReflect.Descriptor instead.
func (*Quarantine) Descriptor() ([]byte, []int) {
	return file_kagal_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Quarantine) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Quarantine) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

var File_kagal_v1_agent_proto protoreflect.FileDescriptor

const file_kagal_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14kagal/v1/agent.proto\x12\bkagal.v1\x1a\x1cgoogle/protobuf/struct.proto\"Y\n" +
	"\x05Hello\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"boot_count\x18\x02 \x01(\rR\tbootCount\x12\x1b\n" +
	"\thw_serial\x18\x03 \x01(\tR\bhwSerial\"U\n" +
	"\fStatusReport\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12+\n" +
	"\x04meta\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04meta\"C\n" +
	"\n" +
	"Quarantine\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"claim_code\x18\x02 \x01(\tR\tclaimCodeB$Z\"kagal.dev/pkg/proto/kagal/v1;kagalb\x06proto3"

var (
	file_kagal_v1_agent_proto_rawDescOnce sync.Once
	file_kagal_v1_agent_proto_rawDescData []byte
)

func file_kagal_v1_agent_proto_rawDescGZIP() []byte {
	file_kagal_v1_agent_proto_rawDescOnce.Do(func() {
		file_kagal_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kagal_v1_agent_proto_rawDesc), len(file_kagal_v1_agent_proto_rawDesc)))
	})
	return file_kagal_v1_agent_proto_rawDescData
}

var file_kagal_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kagal_v1_agent_proto_goTypes = []any{
	(*Hello)(nil),           // 0: kagal.v1.Hello
	(*StatusReport)(nil),    // 1: kagal.v1.StatusReport
	(*Quarantine)(nil),      // 2: kagal.v1.Quarantine
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_kagal_v1_agent_proto_depIdxs = []int32{
	3, // 0: kagal.v1.StatusReport.meta:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kagal_v1_agent_proto_init() }
func file_kagal_v1_agent_proto_init() {
	if File_kagal_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kagal_v1_agent_proto_rawDesc), len(file_kagal_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kagal_v1_agent_proto_goTypes,
		DependencyIndexes: file_kagal_v1_agent_proto_depIdxs,
		MessageInfos:      file_kagal_v1_agent_proto_msgTypes,
	}.Build()
	File_kagal_v1_agent_proto = out.File
	file_kagal_v1_agent_proto_goTypes = nil
	file_kagal_v1_agent_proto_depIdxs = nil
}
