// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kagal/v1/envelope.proto

package kagal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error signals a protocol-level error from server to agent.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_kagal_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_kagal_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ServerMessage is the wire envelope for server-to-agent messages.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Task
	//	*ServerMessage_Nonce
	//	*ServerMessage_Quarantine
	//	*ServerMessage_Error
	//	*ServerMessage_Extension
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_kagal_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_kagal_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetTask() *TaskDispatch {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ServerMessage) GetNonce() *NonceRotate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Nonce); ok {
			return x.Nonce
		}
	}
	return nil
}

func (x *ServerMessage) GetQuarantine() *Quarantine {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Quarantine); ok {
			return x.Quarantine
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetExtension() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Task struct {
	Task *TaskDispatch `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type ServerMessage_Nonce struct {
	Nonce *NonceRotate `protobuf:"bytes,2,opt,name=nonce,proto3,oneof"`
}

type ServerMessage_Quarantine struct {
	Quarantine *Quarantine `protobuf:"bytes,3,opt,name=quarantine,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type ServerMessage_Extension struct {
	Extension *anypb.Any `protobuf:"bytes,15,opt,name=extension,proto3,oneof"`
}

func (*ServerMessage_Task) isServerMessage_Payload() {}

func (*ServerMessage_Nonce) isServerMessage_Payload() {}

func (*ServerMessage_Quarantine) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

func (*ServerMessage_Extension) isServerMessage_Payload() {}

// AgentMessage is the wire envelope for agent-to-server messages.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_TaskResult
	//	*AgentMessage_Status
	//	*AgentMessage_Extension
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_kagal_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_kagal_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentMessage) GetStatus() *StatusReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetExtension() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *StatusReport `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type AgentMessage_Extension struct {
	Extension *anypb.Any `protobuf:"bytes,15,opt,name=extension,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_TaskResult) isAgentMessage_Payload() {}

func (*AgentMessage_Status) isAgentMessage_Payload() {}

func (*AgentMessage_Extension) isAgentMessage_Payload() {}

var File_kagal_v1_envelope_proto protoreflect.FileDescriptor

const file_kagal_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x17kagal/v1/envelope.proto\x12\bkagal.v1\x1a\x19google/protobuf/any.proto\x1a\x14kagal/v1/agent.proto\x1a\x14kagal/v1/nonce.proto\x1a\x13kagal/v1/task.proto\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x02\n" +
	"\rServerMessage\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\x16.kagal.v1.TaskDispatchH\x00R\x04task\x12-\n" +
	"\x05nonce\x18\x02 \x01(\v2\x15.kagal.v1.NonceRotateH\x00R\x05nonce\x126\n" +
	"\n" +
	"quarantine\x18\x03 \x01(\v2\x14.kagal.v1.QuarantineH\x00R\n" +
	"quarantine\x12'\n" +
	"\x05error\x18\x04 \x01(\v2\x0f.kagal.v1.ErrorH\x00R\x05error\x124\n" +
	"\textension\x18\x0f \x01(\v2\x14.google.protobuf.AnyH\x00R\textensionB\t\n" +
	"\apayload\"\xe3\x01\n" +
	"\fAgentMessage\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.kagal.v1.HelloH\x00R\x05hello\x127\n" +
	"\vtask_result\x18\x02 \x01(\v2\x14.kagal.v1.TaskResultH\x00R\n" +
	"taskResult\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x16.kagal.v1.StatusReportH\x00R\x06status\x124\n" +
	"\textension\x18\x0f \x01(\v2\x14.google.protobuf.AnyH\x00R\textensionB\t\n" +
	"\apayloadB$Z\"kagal.dev/pkg/proto/kagal/v1;kagalb\x06proto3"

var (
	file_kagal_v1_envelope_proto_rawDescOnce sync.Once
	file_kagal_v1_envelope_proto_rawDescData []byte
)

func file_kagal_v1_envelope_proto_rawDescGZIP() []byte {
	file_kagal_v1_envelope_proto_rawDescOnce.Do(func() {
		file_kagal_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kagal_v1_envelope_proto_rawDesc), len(file_kagal_v1_envelope_proto_rawDesc)))
	})
	return file_kagal_v1_envelope_proto_rawDescData
}

var file_kagal_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kagal_v1_envelope_proto_goTypes = []any{
	(*Error)(nil),         // 0: kagal.v1.Error
	(*ServerMessage)(nil), // 1: kagal.v1.ServerMessage
	(*AgentMessage)(nil),  // 2: kagal.v1.AgentMessage
	(*TaskDispatch)(nil),  // 3: kagal.v1.TaskDispatch
	(*NonceRotate)(nil),   // 4: kagal.v1.NonceRotate
	(*Quarantine)(nil),    // 5: kagal.v1.Quarantine
	(*anypb.Any)(nil),     // 6: google.protobuf.Any
	(*Hello)(nil),         // 7: kagal.v1.Hello
	(*TaskResult)(nil),    // 8: kagal.v1.TaskResult
	(*StatusReport)(nil),  // 9: kagal.v1.StatusReport
}
var file_kagal_v1_envelope_proto_depIdxs = []int32{
	3, // 0: kagal.v1.ServerMessage.task:type_name -> kagal.v1.TaskDispatch
	4, // 1: kagal.v1.ServerMessage.nonce:type_name -> kagal.v1.NonceRotate
	5, // 2: kagal.v1.ServerMessage.quarantine:type_name -> kagal.v1.Quarantine
	0, // 3: kagal.v1.ServerMessage.error:type_name -> kagal.v1.Error
	6, // 4: kagal.v1.ServerMessage.extension:type_name -> google.protobuf.Any
	7, // 5: kagal.v1.AgentMessage.hello:type_name -> kagal.v1.Hello
	8, // 6: kagal.v1.AgentMessage.task_result:type_name -> kagal.v1.TaskResult
	9, // 7: kagal.v1.AgentMessage.status:type_name -> kagal.v1.StatusReport
	6, // 8: kagal.v1.AgentMessage.extension:type_name -> google.protobuf.Any
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_kagal_v1_envelope_proto_init() }
func file_kagal_v1_envelope_proto_init() {
	if File_kagal_v1_envelope_proto != nil {
		return
	}
	file_kagal_v1_agent_proto_init()
	file_kagal_v1_nonce_proto_init()
	file_kagal_v1_task_proto_init()
	file_kagal_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Task)(nil),
		(*ServerMessage_Nonce)(nil),
		(*ServerMessage_Quarantine)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Extension)(nil),
	}
	file_kagal_v1_envelope_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_TaskResult)(nil),
		(*AgentMessage_Status)(nil),
		(*AgentMessage_Extension)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kagal_v1_envelope_proto_rawDesc), len(file_kagal_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kagal_v1_envelope_proto_goTypes,
		DependencyIndexes: file_kagal_v1_envelope_proto_depIdxs,
		MessageInfos:      file_kagal_v1_envelope_proto_msgTypes,
	}.Build()
	File_kagal_v1_envelope_proto = out.File
	file_kagal_v1_envelope_proto_goTypes = nil
	file_kagal_v1_envelope_proto_depIdxs = nil
}
