// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kagal/v1/nonce.proto

package kagal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NonceRotate rotates the agent's nonce.
type NonceRotate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonceRotate) Reset() {
	*x = NonceRotate{}
	mi := &file_kagal_v1_nonce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonceRotate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceRotate) ProtoMessage() {}

func (x *NonceRotate) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_nonce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceRotate.ProtoReflect.Descriptor instead.
func (*NonceRotate) Descriptor() ([]byte, []int) {
	return file_kagal_v1_nonce_proto_rawDescGZIP(), []int{0}
}

func (x *NonceRotate) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

var File_kagal_v1_nonce_proto protoreflect.FileDescriptor

const file_kagal_v1_nonce_proto_rawDesc = "" +
	"\n" +
	"\x14kagal/v1/nonce.proto\x12\bkagal.v1\"#\n" +
	"\vNonceRotate\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonceB$Z\"kagal.dev/pkg/proto/kagal/v1;kagalb\x06proto3"

var (
	file_kagal_v1_nonce_proto_rawDescOnce sync.Once
	file_kagal_v1_nonce_proto_rawDescData []byte
)

func file_kagal_v1_nonce_proto_rawDescGZIP() []byte {
	file_kagal_v1_nonce_proto_rawDescOnce.Do(func() {
		file_kagal_v1_nonce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kagal_v1_nonce_proto_rawDesc), len(file_kagal_v1_nonce_proto_rawDesc)))
	})
	return file_kagal_v1_nonce_proto_rawDescData
}

var file_kagal_v1_nonce_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kagal_v1_nonce_proto_goTypes = []any{
	(*NonceRotate)(nil), // 0: kagal.v1.NonceRotate
}
var file_kagal_v1_nonce_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kagal_v1_nonce_proto_init() }
func file_kagal_v1_nonce_proto_init() {
	if File_kagal_v1_nonce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kagal_v1_nonce_proto_rawDesc), len(file_kagal_v1_nonce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kagal_v1_nonce_proto_goTypes,
		DependencyIndexes: file_kagal_v1_nonce_proto_depIdxs,
		MessageInfos:      file_kagal_v1_nonce_proto_msgTypes,
	}.Build()
	File_kagal_v1_nonce_proto = out.File
	file_kagal_v1_nonce_proto_goTypes = nil
	file_kagal_v1_nonce_proto_depIdxs = nil
}
