// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kagal/v1/registry.proto

package kagal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KagalRole identifies the caller type resolved from
// the certificate Subject DN.
type KagalRole int32

const (
	KagalRole_KAGAL_ROLE_UNSPECIFIED KagalRole = 0
	KagalRole_KAGAL_ROLE_AGENT       KagalRole = 1
	KagalRole_KAGAL_ROLE_OPERATOR    KagalRole = 2
)

// Enum value maps for KagalRole.
var (
	KagalRole_name = map[int32]string{
		0: "KAGAL_ROLE_UNSPECIFIED",
		1: "KAGAL_ROLE_AGENT",
		2: "KAGAL_ROLE_OPERATOR",
	}
	KagalRole_value = map[string]int32{
		"KAGAL_ROLE_UNSPECIFIED": 0,
		"KAGAL_ROLE_AGENT":       1,
		"KAGAL_ROLE_OPERATOR":    2,
	}
)

func (x KagalRole) Enum() *KagalRole {
	p := new(KagalRole)
	*p = x
	return p
}

func (x KagalRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KagalRole) Descriptor() protoreflect.EnumDescriptor {
	return file_kagal_v1_registry_proto_enumTypes[0].Descriptor()
}

func (KagalRole) Type() protoreflect.EnumType {
	return &file_kagal_v1_registry_proto_enumTypes[0]
}

func (x KagalRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KagalRole.Descriptor instead.
func (KagalRole) EnumDescriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{0}
}

// AgentStatus is the access state resolved by KagalAuth
// from the AgentRecord booleans.
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_NOT_READY   AgentStatus = 1
	AgentStatus_AGENT_STATUS_READY       AgentStatus = 2
	AgentStatus_AGENT_STATUS_QUARANTINED AgentStatus = 3
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_NOT_READY",
		2: "AGENT_STATUS_READY",
		3: "AGENT_STATUS_QUARANTINED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_NOT_READY":   1,
		"AGENT_STATUS_READY":       2,
		"AGENT_STATUS_QUARANTINED": 3,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kagal_v1_registry_proto_enumTypes[1].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_kagal_v1_registry_proto_enumTypes[1]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{1}
}

// AgentRecord represents agent state. Stored in
// agent:<agentID> KV entries and returned by fleet
// query endpoints.
type AgentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Quarantined   bool                   `protobuf:"varint,2,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	LastSeen      string                 `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Groups        []string               `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRecord) Reset() {
	*x = AgentRecord{}
	mi := &file_kagal_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRecord) ProtoMessage() {}

func (x *AgentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRecord.ProtoReflect.Descriptor instead.
func (*AgentRecord) Descriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRecord) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *AgentRecord) GetQuarantined() bool {
	if x != nil {
		return x.Quarantined
	}
	return false
}

func (x *AgentRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentRecord) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *AgentRecord) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

// NameRecord is the value stored in name:<name>
// KV entries.
type NameRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRecord) Reset() {
	*x = NameRecord{}
	mi := &file_kagal_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRecord) ProtoMessage() {}

func (x *NameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRecord.ProtoReflect.Descriptor instead.
func (*NameRecord) Descriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *NameRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// CertRecord is the value stored in cert:<sha256>
// KV entries.
type CertRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRecord) Reset() {
	*x = CertRecord{}
	mi := &file_kagal_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRecord) ProtoMessage() {}

func (x *CertRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRecord.ProtoReflect.Descriptor instead.
func (*CertRecord) Descriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *CertRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CertRecord) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

// RevokedRecord is the value stored in
// revoked:<sha256> KV entries.
type RevokedRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedAt     string                 `protobuf:"bytes,1,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CertNotAfter  string                 `protobuf:"bytes,3,opt,name=cert_not_after,json=certNotAfter,proto3" json:"cert_not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokedRecord) Reset() {
	*x = RevokedRecord{}
	mi := &file_kagal_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokedRecord) ProtoMessage() {}

func (x *RevokedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokedRecord.ProtoReflect.Descriptor instead.
func (*RevokedRecord) Descriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RevokedRecord) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

func (x *RevokedRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokedRecord) GetCertNotAfter() string {
	if x != nil {
		return x.CertNotAfter
	}
	return ""
}

// AuthResult is the resolved identity and state
// returned by kagalAuth().
type AuthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Role          KagalRole              `protobuf:"varint,2,opt,name=role,proto3,enum=kagal.v1.KagalRole" json:"role,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	CertExpired   bool                   `protobuf:"varint,4,opt,name=cert_expired,json=certExpired,proto3" json:"cert_expired,omitempty"`
	AgentStatus   AgentStatus            `protobuf:"varint,5,opt,name=agent_status,json=agentStatus,proto3,enum=kagal.v1.AgentStatus" json:"agent_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_kagal_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuthResult) GetRole() KagalRole {
	if x != nil {
		return x.Role
	}
	return KagalRole_KAGAL_ROLE_UNSPECIFIED
}

func (x *AuthResult) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AuthResult) GetCertExpired() bool {
	if x != nil {
		return x.CertExpired
	}
	return false
}

func (x *AuthResult) GetAgentStatus() AgentStatus {
	if x != nil {
		return x.AgentStatus
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

// RegistryRecord is a tagged union of all KV value
// types in the agent registry namespace.
type RegistryRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Record:
	//
	//	*RegistryRecord_Name
	//	*RegistryRecord_Agent
	//	*RegistryRecord_Cert
	//	*RegistryRecord_Revoked
	Record        isRegistryRecord_Record `protobuf_oneof:"record"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRecord) Reset() {
	*x = RegistryRecord{}
	mi := &file_kagal_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRecord) ProtoMessage() {}

func (x *RegistryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRecord.ProtoReflect.Descriptor instead.
func (*RegistryRecord) Descriptor() ([]byte, []int) {
	return file_kagal_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegistryRecord) GetRecord() isRegistryRecord_Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *RegistryRecord) GetName() *NameRecord {
	if x != nil {
		if x, ok := x.Record.(*RegistryRecord_Name); ok {
			return x.Name
		}
	}
	return nil
}

func (x *RegistryRecord) GetAgent() *AgentRecord {
	if x != nil {
		if x, ok := x.Record.(*RegistryRecord_Agent); ok {
			return x.Agent
		}
	}
	return nil
}

func (x *RegistryRecord) GetCert() *CertRecord {
	if x != nil {
		if x, ok := x.Record.(*RegistryRecord_Cert); ok {
			return x.Cert
		}
	}
	return nil
}

func (x *RegistryRecord) GetRevoked() *RevokedRecord {
	if x != nil {
		if x, ok := x.Record.(*RegistryRecord_Revoked); ok {
			return x.Revoked
		}
	}
	return nil
}

type isRegistryRecord_Record interface {
	isRegistryRecord_Record()
}

type RegistryRecord_Name struct {
	Name *NameRecord `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type RegistryRecord_Agent struct {
	Agent *AgentRecord `protobuf:"bytes,2,opt,name=agent,proto3,oneof"`
}

type RegistryRecord_Cert struct {
	Cert *CertRecord `protobuf:"bytes,3,opt,name=cert,proto3,oneof"`
}

type RegistryRecord_Revoked struct {
	Revoked *RevokedRecord `protobuf:"bytes,4,opt,name=revoked,proto3,oneof"`
}

func (*RegistryRecord_Name) isRegistryRecord_Record() {}

func (*RegistryRecord_Agent) isRegistryRecord_Record() {}

func (*RegistryRecord_Cert) isRegistryRecord_Record() {}

func (*RegistryRecord_Revoked) isRegistryRecord_Record() {}

var File_kagal_v1_registry_proto protoreflect.FileDescriptor

const file_kagal_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x17kagal/v1/registry.proto\x12\bkagal.v1\"\x8e\x01\n" +
	"\vAgentRecord\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12 \n" +
	"\vquarantined\x18\x02 \x01(\bR\vquarantined\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\tR\blastSeen\x12\x16\n" +
	"\x06groups\x18\x05 \x03(\tR\x06groups\"'\n" +
	"\n" +
	"NameRecord\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"L\n" +
	"\n" +
	"CertRecord\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rregistered_at\x18\x02 \x01(\tR\fregisteredAt\"l\n" +
	"\rRevokedRecord\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x01 \x01(\tR\trevokedAt\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12$\n" +
	"\x0ecert_not_after\x18\x03 \x01(\tR\fcertNotAfter\"\xcf\x01\n" +
	"\n" +
	"AuthResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x04role\x18\x02 \x01(\x0e2\x13.kagal.v1.KagalRoleR\x04role\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x12!\n" +
	"\fcert_expired\x18\x04 \x01(\bR\vcertExpired\x128\n" +
	"\fagent_status\x18\x05 \x01(\x0e2\x15.kagal.v1.AgentStatusR\vagentStatus\"\xd6\x01\n" +
	"\x0eRegistryRecord\x12*\n" +
	"\x04name\x18\x01 \x01(\v2\x14.kagal.v1.NameRecordH\x00R\x04name\x12-\n" +
	"\x05agent\x18\x02 \x01(\v2\x15.kagal.v1.AgentRecordH\x00R\x05agent\x12*\n" +
	"\x04cert\x18\x03 \x01(\v2\x14.kagal.v1.CertRecordH\x00R\x04cert\x123\n" +
	"\arevoked\x18\x04 \x01(\v2\x17.kagal.v1.RevokedRecordH\x00R\arevokedB\b\n" +
	"\x06record*V\n" +
	"\tKagalRole\x12\x1a\n" +
	"\x16KAGAL_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KAGAL_ROLE_AGENT\x10\x01\x12\x17\n" +
	"\x13KAGAL_ROLE_OPERATOR\x10\x02*}\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AGENT_STATUS_NOT_READY\x10\x01\x12\x16\n" +
	"\x12AGENT_STATUS_READY\x10\x02\x12\x1c\n" +
	"\x18AGENT_STATUS_QUARANTINED\x10\x03B$Z\"kagal.dev/pkg/proto/kagal/v1;kagalb\x06proto3"

var (
	file_kagal_v1_registry_proto_rawDescOnce sync.Once
	file_kagal_v1_registry_proto_rawDescData []byte
)

func file_kagal_v1_registry_proto_rawDescGZIP() []byte {
	file_kagal_v1_registry_proto_rawDescOnce.Do(func() {
		file_kagal_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kagal_v1_registry_proto_rawDesc), len(file_kagal_v1_registry_proto_rawDesc)))
	})
	return file_kagal_v1_registry_proto_rawDescData
}

var file_kagal_v1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kagal_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kagal_v1_registry_proto_goTypes = []any{
	(KagalRole)(0),         // 0: kagal.v1.KagalRole
	(AgentStatus)(0),       // 1: kagal.v1.AgentStatus
	(*AgentRecord)(nil),    // 2: kagal.v1.AgentRecord
	(*NameRecord)(nil),     // 3: kagal.v1.NameRecord
	(*CertRecord)(nil),     // 4: kagal.v1.CertRecord
	(*RevokedRecord)(nil),  // 5: kagal.v1.RevokedRecord
	(*AuthResult)(nil),     // 6: kagal.v1.AuthResult
	(*RegistryRecord)(nil), // 7: kagal.v1.RegistryRecord
}
var file_kagal_v1_registry_proto_depIdxs = []int32{
	0, // 0: kagal.v1.AuthResult.role:type_name -> kagal.v1.KagalRole
	1, // 1: kagal.v1.AuthResult.agent_status:type_name -> kagal.v1.AgentStatus
	3, // 2: kagal.v1.RegistryRecord.name:type_name -> kagal.v1.NameRecord
	2, // 3: kagal.v1.RegistryRecord.agent:type_name -> kagal.v1.AgentRecord
	4, // 4: kagal.v1.RegistryRecord.cert:type_name -> kagal.v1.CertRecord
	5, // 5: kagal.v1.RegistryRecord.revoked:type_name -> kagal.v1.RevokedRecord
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kagal_v1_registry_proto_init() }
func file_kagal_v1_registry_proto_init() {
	if File_kagal_v1_registry_proto != nil {
		return
	}
	file_kagal_v1_registry_proto_msgTypes[5].OneofWrappers = []any{
		(*RegistryRecord_Name)(nil),
		(*RegistryRecord_Agent)(nil),
		(*RegistryRecord_Cert)(nil),
		(*RegistryRecord_Revoked)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kagal_v1_registry_proto_rawDesc), len(file_kagal_v1_registry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kagal_v1_registry_proto_goTypes,
		DependencyIndexes: file_kagal_v1_registry_proto_depIdxs,
		EnumInfos:         file_kagal_v1_registry_proto_enumTypes,
		MessageInfos:      file_kagal_v1_registry_proto_msgTypes,
	}.Build()
	File_kagal_v1_registry_proto = out.File
	file_kagal_v1_registry_proto_goTypes = nil
	file_kagal_v1_registry_proto_depIdxs = nil
}
