// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kagal/v1/task.proto

package kagal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus represents the lifecycle state of a task.
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 1
	TaskStatus_TASK_STATUS_DISPATCHED  TaskStatus = 2
	TaskStatus_TASK_STATUS_OK          TaskStatus = 3
	TaskStatus_TASK_STATUS_ERROR       TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_QUEUED",
		2: "TASK_STATUS_DISPATCHED",
		3: "TASK_STATUS_OK",
		4: "TASK_STATUS_ERROR",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_QUEUED":      1,
		"TASK_STATUS_DISPATCHED":  2,
		"TASK_STATUS_OK":          3,
		"TASK_STATUS_ERROR":       4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kagal_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_kagal_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_kagal_v1_task_proto_rawDescGZIP(), []int{0}
}

// TaskDispatch dispatches a task from server to agent.
type TaskDispatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDispatch) Reset() {
	*x = TaskDispatch{}
	mi := &file_kagal_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDispatch) ProtoMessage() {}

func (x *TaskDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDispatch.ProtoReflect.Descriptor instead.
func (*TaskDispatch) Descriptor() ([]byte, []int) {
	return file_kagal_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDispatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDispatch) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TaskDispatch) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// TaskResult reports a task outcome from agent to server.
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=kagal.v1.TaskStatus" json:"status,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_kagal_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_kagal_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_kagal_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_kagal_v1_task_proto protoreflect.FileDescriptor

const file_kagal_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x13kagal/v1/task.proto\x12\bkagal.v1\x1a\x1cgoogle/protobuf/struct.proto\"g\n" +
	"\fTaskDispatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\"\x8d\x01\n" +
	"\n" +
	"TaskResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.kagal.v1.TaskStatusR\x06status\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\x88\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x01\x12\x1a\n" +
	"\x16TASK_STATUS_DISPATCHED\x10\x02\x12\x12\n" +
	"\x0eTASK_STATUS_OK\x10\x03\x12\x15\n" +
	"\x11TASK_STATUS_ERROR\x10\x04B$Z\"kagal.dev/pkg/proto/kagal/v1;kagalb\x06proto3"

var (
	file_kagal_v1_task_proto_rawDescOnce sync.Once
	file_kagal_v1_task_proto_rawDescData []byte
)

func file_kagal_v1_task_proto_rawDescGZIP() []byte {
	file_kagal_v1_task_proto_rawDescOnce.Do(func() {
		file_kagal_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kagal_v1_task_proto_rawDesc), len(file_kagal_v1_task_proto_rawDesc)))
	})
	return file_kagal_v1_task_proto_rawDescData
}

var file_kagal_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kagal_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kagal_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),         // 0: kagal.v1.TaskStatus
	(*TaskDispatch)(nil),    // 1: kagal.v1.TaskDispatch
	(*TaskResult)(nil),      // 2: kagal.v1.TaskResult
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_kagal_v1_task_proto_depIdxs = []int32{
	3, // 0: kagal.v1.TaskDispatch.params:type_name -> google.protobuf.Struct
	0, // 1: kagal.v1.TaskResult.status:type_name -> kagal.v1.TaskStatus
	3, // 2: kagal.v1.TaskResult.data:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kagal_v1_task_proto_init() }
func file_kagal_v1_task_proto_init() {
	if File_kagal_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kagal_v1_task_proto_rawDesc), len(file_kagal_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kagal_v1_task_proto_goTypes,
		DependencyIndexes: file_kagal_v1_task_proto_depIdxs,
		EnumInfos:         file_kagal_v1_task_proto_enumTypes,
		MessageInfos:      file_kagal_v1_task_proto_msgTypes,
	}.Build()
	File_kagal_v1_task_proto = out.File
	file_kagal_v1_task_proto_goTypes = nil
	file_kagal_v1_task_proto_depIdxs = nil
}
